; PlatformIO Project Configuration File
; M5Cardputer LG TV Remote firmware

[env:cardputer]
platform = espressif32@6.7.0
board = m5stack-stamps3
framework = arduino

board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.partitions = default.csv

lib_deps =
    m5stack/M5Cardputer @ ^1.0.3
    crankyoldgit/IRremoteESP8266 @ ^2.8.6

build_flags =
    -DCORE_DEBUG_LEVEL=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -std=gnu++17
    -Iinclude
    -Isrc

build_unflags =
    -std=gnu++11

monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time
upload_speed = 921600
